Proyect-PF/unBardo_design

api/.sequelizerc
api/config/config.js
api/index.ts
api/package-lock.json
api/package.json
api/src/app.ts
api/src/database/migrations/20230201125704-create-product.js
api/src/db.ts
api/src/index.ts
api/src/models/Product.js
api/src/models/index.js
api/tsconfig.json

La base de datos esta configurada, para usar SEQUELIZE CLI, con el comando 
npx sequelize-cli model:generate --name User --attributes firstName:string,lastName:string,email:string
A us vez falta crear la configuracion del archivo app.ts, el cual va a tener configurado los distintos middelwares de terceros
ya se pueden crear los modelos de sequelize

DataBase configuration complete a 60% State:Usable

---

api/src/models/Product.js

prueba de modificar modelo producto en back

change example in model product

---

api/src/models/Orders.ts

model orders inicial

---

api/src/models/Product.ts

Se creo el modelo product en sequelize. Falta habilitar las asociaciones con categorias y colores.

Creacion model product

---

api/src/models/Orders.ts

Se agrega las asociaciones entre los modelos Orders y Payment, así como con OrderDetails.

Add associations to Orders and Payment models.

---

api/src/models/Category.ts
api/src/models/Colour.ts
api/src/models/Product.ts

Modificación y creación de tablas intermedias de los modelos Product, Colour y Category.

Modificación models product, category y colour

---

api/index.ts
api/src/models/Category.ts
api/src/models/Product.ts
api/src/models/ProductColour.ts

Comentadas las asociacicones que generaban errores, back en funcionamiento

asociations comments

---

api/src/Product/controllers/deleteProduct.ts
api/src/Product/controllers/getProduct.route.ts
api/src/Product/controllers/postProduct.ts
api/src/Product/controllers/putProductr.ts
api/src/Product/routes/index.ts
api/src/routes.ts

Se crearon las rutas Delete, Put, Post y Get de Product pero con los controllers vacios.

Creacion de rutas de Product sin las funcionalidades

---

client/src/App.tsx
client/src/layouts/Footer/Footer.tsx
client/src/layouts/Navbar/Navbar.tsx
client/src/layouts/Sidebar/Sidebar.tsx

Agregue funcionalidad para abrir y cerrar el sidebar falta pulir más

agregando funcionalidad de abrir y cerrar el sidebar

---

api/config/config.js
api/src/models/Image.ts
api/src/models/OrderDetail.ts
api/src/models/Orders.ts
api/src/models/Product.ts

Se modificaron los modelos Order, OrderDetail e Image

Modelos order detail image

---

api/config/config.js
api/index.ts
api/src/Admin/controllers/getAdmins.ts
api/src/Admin/controllers/postAdmin.ts
api/src/Admin/middlewares/createAdmin.ts
api/src/Admin/routes/index.ts
api/src/models/Admin.ts

Se optimiza Post admin con comentarios, se empieza a crear la ruta para obtener administraciones

POST ADMIN end and process GET ADMIN

---

api/src/Product/controllers/getProduct.ts
api/src/Product/middleware/getAllProductsInfo.ts
api/src/Product/middleware/getProductInfo.ts
api/src/Product/routes/index.ts

Se creo la ruta get de product. Si se envía el id por query en la ruta busca al producto relacionado a ese id, y si no se envía el id busca todos los productos.

Creacion de ruta get de product

---

api/src/models/Admin.ts
api/src/models/Category.ts
api/src/models/Colour.ts
api/src/models/Comment.ts
api/src/models/Image.ts
api/src/models/OrderDetail.ts
api/src/models/Orders.ts
api/src/models/Product.ts
api/src/models/ProductColour.ts

Associations

---

api/src/Product/controllers/searchProduct.ts
api/src/Product/middleware/searchByName.ts
api/src/Product/routes/index.ts

Se creo el search por name de product por medio de la direccion /product/search por param. Falta ajustar que discrimine mayusculas y minusculas

creacion de search product

---

api/src/Category/controllers/getCategory.ts
api/src/Category/controllers/postCategory.ts
api/src/Category/index.ts
api/src/Category/middlewares/createCategory.ts
api/src/Category/middlewares/getAllCategoryInfo.ts
api/src/Category/middlewares/getCategoryInfo.ts
api/src/Category/routes/index.ts

Añadir rutas de categoría, middlewares, controladores. Implementar los métodos GET y POST para el endpoint de categoría, getCategoryInfo y getAllProductsInfo para obtener información de la categoría y createCategory para crear una nueva categoría. Crear instanceOfCategory para conectarse al modelo Category en la base de datos.

Add category routes, middlewares, and controllers.

---

api/index.ts
api/src/Product/controllers/getProduct.ts
api/src/Product/controllers/postProduct.ts
api/src/Product/controllers/searchProduct.ts
api/src/Product/middleware/cretaeProduct.ts
api/src/Product/middleware/getAllProductsInfo.ts
api/src/Product/middleware/getProductInfo.ts
api/src/Product/middleware/searchByName.ts

Se modificaron las rutas relacionadas a product. Las rutas de search (por name), y get (por id y todos los productos) product se modificaron para retornar solo:
"id"
"name"
"description":
"size"
"show_in_shop"
"price"

modificacion rutas de product

---

api/src/Product/controllers/orderByPrice.ts
api/src/Product/middleware/getOrderByPrice.ts
api/src/Product/routes/index.ts

Si recibe por params la palabra “ASC” o “DESC” (indistinto si es en mayúscula o minúsculas) para ordenar los precios de manear ascendente o descendente. Ruta /products/price

creacion de ruta de ordenamiento por precio

---

api/package-lock.json
api/package.json
api/src/Product/controllers/controllers_product.ts

Se modifico la busqueda de producto por name, para que si no encuentra ningun producto envie un status 400

modificacion search product

---

api/src/Orders/controllers/controllers_order.ts

se realizaron modificaciones en el controller de mercadopago

---

api/README.md
api/src/Orders/controllers/controllers_order.ts
api/src/Orders/routes/index.ts

Se modifico el readme, donde se agregaron las rutas de orders relacionadas a mercado pago, y se agrego una variable de entorno

modificaciones carpeta order y readme

---

api/src/Orders/controllers/controllers_order.ts

Obtencion de la ultima orden del usuario para enviar a mercado pago en controllers_orders

Obtencion de la ultima orden del usuario

---

api/README.md
api/src/Orders/controllers/controllers_order.ts

La ruta es /orders y recibe id y status por query

Creacion de la ruta UPDATE de order

---

client/package-lock.json
client/package.json
client/src/components/payment/FormCheckout.tsx
client/src/utils/FormPayment/validation.tsx

Se integro Mercado Pago al carrito - Casi terminado

mercado pago integrado al carrito funcionando

---

api/src/Orders/controllers/controllers_mercadopago.ts

Se agrego tambien el update del stock de los talles si la compra se realiza exitosamente

Se paso lo de mercadopago a otro controller nuevo

---

api/src/Orders/controllers/controllers_mercadopago.ts
api/src/Orders/controllers/controllers_order.ts

Borrado del order con status cart al generar una nueva orden con status cart

Mantener un solo carrito por usuario

---

api/src/controllers/auth.controller.ts
api/src/controllers/user.controller.ts
api/src/database/models/user.model.ts
api/src/routes/product.routes.ts
api/src/types/index.ts
client/src/types/types.tsx

Se crea tipado de user en el backend, se crea una nueva variable al modelo del usuario, para que sea subscripto

users emails and newLetters

---

api/src/controllers/shipment.controller.ts
api/src/routes/shipment.routes.ts

Se obtiene de la api LocationIQ la distancia para el envío y se realiza el calcula del costo segun se encuentre a menos de 100km, menos de 500km, menos de 1000km y mas de 1000km

"Se agrego la ruta para obtener el costo de envio"
